server:
  port: 7700

## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://101.132.127.242:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 46FD38a27fab4f8dAB57d203aA98dCF9@201032Tz
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: MySQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect